apiVersion: v2
name: core-dump-handler
description: A Helm chart for deploying a core dump management system to Kubernetes
keywords:
  - coredump
  - post-mortem
  - observability
sources:
  - https://github.com/ibm/core-dump-handler

type: application

version: v5.0.3

appVersion: "v5.0.3"

icon: https://raw.githubusercontent.com/No9/core-dump-handler/master/assets/handle-with-care-svgrepo-com.svg

maintainers:
  - name: No9
    email: anton@venshare.com
    url: https://github.com/No9/
  - name: timbuchwaldt
    email: tim@buchwaldt.ws
    url: https://github.com/timbuchwaldt/

annotations:
  artifacthub.io/changes: |
    - Added linting for build process
  artifacthub.io/license: MIT
