apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: {{ .Values.daemonset.name }}
spec:
  selector:
    matchLabels:
      name: {{ .Values.daemonset.label }}
  template:
    metadata:
      labels:
        name: {{ .Values.daemonset.label }}
    spec:
      containers:
      - name: coredump-container
        image: {{ .Values.image.repository }}
        securityContext:
          privileged: true
        volumeMounts:
        - name: host-volume
          mountPath:  {{ .Values.daemonset.hostDirectory }}
          mountPropagation: Bidirectional
        env:
          - name: COMP_LOG_LEVEL
            value: {{ .Values.daemonset.composerLogLevel }}
          - name: HOST_DIR
            value: {{ .Values.daemonset.hostDirectory }}
          - name: SUID_DUMPABLE
            value: {{ .Values.daemonset.suidDumpable | quote }}
          - name: S3_ACCESS_KEY
            valueFrom:
              secretKeyRef:
                name: s3config
                key: s3AccessKey
          - name: S3_SECRET
            valueFrom:
              secretKeyRef:
                name: s3config
                key: s3Secret
          - name: S3_BUCKET_NAME
            valueFrom:
              secretKeyRef:
                name: s3config
                key: s3BucketName
          - name: S3_REGION
            valueFrom:
              secretKeyRef:
                name: s3config
                key: s3Region
          - name: VENDOR
            value: {{ .Values.daemonset.vendor }}
          - name: INTERVAL
            value: {{ .Values.daemonset.interval | quote }}
        command: ["/app/core-dump-agent"]
        lifecycle:
          preStop:
            exec:
              command: ["/app/core-dump-agent", "remove"]
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "ibm-core-dump-handler.serviceAccountName" . }}
      volumes:
      - name: host-volume
        persistentVolumeClaim:
          claimName:  host-path-pvc
