[package]
name = "core-dump-agent"
version = "0.1.0"
authors = ["Anthony Whalley <anton@venshare.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dotenv  = "0.15.0"
env_logger = "0.8.3"
log = "0.4.14"
rust-s3 = "0.26.0"
advisory-lock = "0.3.0"
tokio-cron-scheduler = "0.2.3"
tokio = { version = "1", features = ["macros", "time", "rt"] }
anyhow = "1.0.44"
