replicaCount: 1

image:
  registry: quay.io
  repository: icdh/core-dump-handler
  tag: main
  pullPolicy: Always
  request_mem: "64Mi"
  request_cpu: "250m"
  limit_mem: "128Mi"
  limit_cpu: "500m"

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

# Size of the Persistent volume to create
hostStorage: 1Gi
coreStorage: 10Gi
storageClass: hostclass


daemonset:
  name: "core-dump-handler"
  label: "core-dump-ds"
  hostDirectory: "/var/mnt/core-dump-handler"
  coreDirectory: "/var/mnt/core-dump-handler/cores"
  composerLogLevel: "Warn"
  suidDumpable: 2
  vendor: default
  schedule: "1/60 * * * * *"
  # useINotify: true
  # interval: 1230
  composerIgnoreCrio: false
  composerCrioImageCmd: "img"
  DeployCrioConfig: false
  includeCrioExe: false
  # S3 access
  manageStoreSecret: false
  extraEnvVars: ""
serviceAccount:
  create: true
  name: "core-dump-admin"

clusterRole:
  name: "core-dump-event-reporter"

clusterRoleBinding:
  name: "core-dump-event-report"

# nodeSelector & affinity for the daemonset's pod assignment
# https://kubernetes.io/docs/concepts/workloads/controllers/daemonset/#running-pods-on-select-nodes
nodeSelector: {}
# eg
# gpu-enabled: true
affinity: {}

# Tolerations for the daemonset's pod assignment
# ref: https://kubernetes.io/docs/concepts/configuration/taint-and-toleration/
tolerations: {}
# eg
# - key: "key"
#   operator: "Equal"
#   value: "value"
#   effect: "NoSchedule"
