replicaCount: 1

image:
  repository: quay.io/icdh/core-dump-handler:do-support@sha256:7ef66f4cf085361e310f9a7457b9729809ae060fb22804548837c933fd119af2
  pullPolicy: Always

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

# Size of the Persistent volume to create
storage: 1Gi

daemonset:
    name: "core-dump-handler"
    label: "core-dump-ds"
    hostDirectory: "/var/mnt/core-dump-handler"
    composerLogLevel: "Warn"
    suidDumpable: 2
    s3AccessKey : XXX
    s3Secret : XXX
    s3BucketName : XXX
    s3Region : XXX
    vendor: default
    interval: 60000
    composerIgnoreCrio: false
    composerCrioImageCmd: "img"
    DeployCrioConfig: false
serviceAccount:
  create: true
  name: "core-dump-admin"

clusterRole:
  name: "core-dump-event-reporter"

clusterRoleBinding:
  name: "core-dump-event-report"

# nodeSelector & affinity for the daemonset's pod assignment
# https://kubernetes.io/docs/concepts/workloads/controllers/daemonset/#running-pods-on-select-nodes
nodeSelector: {}
# eg
# gpu-enabled: true
affinity: {}

# Tolerations for the daemonset's pod assignment
# ref: https://kubernetes.io/docs/concepts/configuration/taint-and-toleration/
tolerations: {}
# eg
# - key: "key"
#   operator: "Equal"
#   value: "value"
#   effect: "NoSchedule"
