[package]
name = "core-dump-composer"
version = "0.1.0"
authors = ["Anthony Whalley <anton@venshare.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "3.0.0-beta.5"
advisory-lock = "0.3.0"
uuid = { version = "0.8", features = ["serde", "v4"] }
zip = "0.5.6"
dotenv  = "0.15.0"
log = "0.4.14"
log4rs = "1.0.0"
anyhow = "1.0.40"
serde_json = "1.0.64"
serde_derive = "1.0.125"
hostname = "0.3.1"

[dev-dependencies]
serde = { version = "1", features = ["derive"] }
serde_json = "1"
rand = "0.7.3"
