apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: storage-path-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.coreStorage }}
  storageClassName: {{ .Values.storageClass }}