apiVersion: v1
kind: PersistentVolume
metadata:
  name: core-volume
  labels:
    type: local
spec:
  storageClassName: {{ .Values.storageClass }} 
  capacity:
    storage: {{ .Values.coreStorage }}
  accessModes:
  - ReadWriteOnce 
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: {{ .Values.daemonset.coreDirectory }}
