apiVersion: v1
kind: PersistentVolume
metadata:
  name: host-volume
  labels:
    type: local
spec:
  storageClassName: {{ .Values.storageClass }}
  claimRef:
    name: host-storage-pvc
    namespace: {{ .Release.Namespace }}
  capacity:
    storage: {{ .Values.hostStorage }}
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: {{ .Values.daemonset.hostDirectory }}
