apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: host-path-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.hostStorage }}
  storageClassName: {{ .Values.storageClass }}
