{{- if .Values.daemonset.manageStoreSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: s3config
type: Opaque
stringData:
{{- if .Values.daemonset.s3Secret }}
  s3Secret: {{ .Values.daemonset.s3Secret }}
{{- end }}
{{- if .Values.daemonset.s3AccessKey }}
  s3AccessKey: {{ .Values.daemonset.s3AccessKey }}
{{- end }}
  s3BucketName: {{ .Values.daemonset.s3BucketName }}
  s3Region: {{ .Values.daemonset.s3Region }}
{{- end }}
