
name: Validate

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Run Rustfmt
      run: cargo clippy
    - name: Run Rustclippy
      run: cargo fmt
    - name: Build
      run: cargo build --verbose
